### ISSUE TITLE
Migration guide for "scroll-lock" users

### ISSUE THREAD

**Issue by klonwar** [fluejs/noscroll#1]
Hi, today I saw that 'scroll-lock' is deprecated. First of all, thank you for your great work, this library is very convenient and flexible.

As I see from the codebase, 'noscroll' is written from scratch and not fully compatible with 'scroll-lock'. For example, `data` attributes are different. In that case, it would be great to see some sort of guide on how to migrate to 'noscroll'. And if there are any features that now work differently or are missing, it'd be great to see a list of them.

Thank you!

**Comment by FL3NKEY** [comment]
Hi! Thank you for your interest!

#2
